name: Scaffold a new service
on:
  workflow_dispatch:
    secrets:
      ORG_ADMIN_TOKEN:
        required: true
jobs:
  print-message:
    runs-on: ubuntu-latest

    steps:
    - name: Print test passed
      run: echo "test passed"
