name: Scaffold a new service
on:
  workflow_dispatch:
    inputs:
      port_payload:
        required: true
        description: "Port's payload, including details for who triggered the action and general context (blueprint, run id, etc...)"
        type: string
    secrets:
      ORG_ADMIN_TOKEN:
        required: true
jobs:
  print-message:
    runs-on: ubuntu-latest

    steps:
    - name: Print test passed
      run: echo "test passed"
