name: Notify when service becomes unhealthy

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: "The unhealthy service's name"
        required: true
        type: string

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Slack
        env:
          SLACK_AUTH_TOKEN: ${{ secrets.SLACK_AUTH_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        run: |
          curl -X POST https://slack.com/api/chat.postMessage -H "Authorization: Bearer $SLACK_AUTH_TOKEN" -H "Content-Type: application/json" -d '{"channel": "$SLACK_CHANNEL_ID","text": "Hello from the user token!"}'
