name: Test team output

on:
  workflow_dispatch:
    inputs:
      port_payload:
        required: true
        description: "the payload"
        type: string
    secrets:
      ORG_ADMIN_TOKEN:
        required: true
      PORT_CLIENT_ID:
        required: true
      PORT_CLIENT_SECRET:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ port_payload }}
